site_name: Ubiq Docs
nav:
    - Home: index.md
    - Getting Started:
        - Getting Ubiq: gettingubiq.md
        - Setting Up VR: settingupvr.md
        - Creating Networked Objects: creatinganetworkedobject.md
        - Object Spawning: spawningobjects.md
        - Testing with Local Loopback: localloopback.md
        - Synchronisation: synchronisation.md
        - Interaction with Ubiq XR: ubiqxrinteraction.md
        - Servers and Rooms: serversandrooms.md
        - Logging: eventlogginggettingstarted.md
    - Tutorials:
      - Creating a 3D Pen: 3dpentutorial.md
      - Server: serversetup.md
    - Advanced:
        - Interaction: xrinteraction.md
        - Logging:
            - Introduction: eventlogging.md
            - Analysis: eventloganalysis.md
            - Questionnaire: eventloggingexperimentquestionnaire.md
            - Unit Tests: eventloggingunittests.md
            - LogCollector Service: eventloggingcollectorservice.md
            - Serialisation and Memory: eventlogserialisation.md
        - Messaging:
            - Introduction: messaging.md
            - Network Ids: networkids.md
            - Generating Unique Ids: generatinguniqueids.md
            - Types: networkidtype.md
            - Reserved IDs: reservedids.md
        - WebRtc: webrtc.md
        - Servers and Rooms:
            - Introduction: serverintroduction.md
            - Server Overview: serveroverview.md
            - Heartbeat and Timeouts: serverheartbeat.md
            - Leaving and Joining: leavingandjoiningrooms.md
        - Bots: botssample.md
    - Programming:
        - Async Design Patterns: asyncdesignpatterns.md
    - Development:
        - Packaging: packaging.md
        - Nexus: nexus.md
    - Meta: mkdocs.md

theme:
    name: readthedocs
